### PR TITLE
add createServer use listen

### PR DESCRIPTION
**Pull request by nickleefly**
cc @yorkie

### CODE REVIEW

**Comment by yorkie** [comment]
Run https://github.com/weflex/javascript/tree/master/packages/eslint-config with your code before catching me to review, thank you :-)

**Comment by nickleefly** [comment]
Eslint still says a few errors, not sure how I should fix the first line. eslint by default doesn't expect no-param-reassign. But this is optional, We can turn if off.

```
   1:1  error  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
   1:1  error  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
   1:1  error  Definition for rule 'react/jsx-quotes' was not found                         react/jsx-quotes
  22:5  error  Assignment to function parameter 'handle'                                    no-param-reassign
  23:5  error  Assignment to function parameter 'route'                                     no-param-reassign
```

**Comment by yorkie** [comment]
@nickleefly run eslint with `--fix` to see what happened, thanks

**Comment by nickleefly** [comment]
@yorkie eslint cant automatically fix problems. The problems are still there.

**Pull request closed without merging**
